home/urls.py
from django.conf.urls import url

from home import views


urlpatterns = [
    url(r'^(?P<reg>[0-9a-zA-Z]+)/*$', views.aircraft_details, name='aircraft_details'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/tasks/*$', views.aircraft_task_list, name='aircraft_task_list'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/tasks/(?P<task_id>[0-9]+)/*$', views.aircraft_task, name='aircraft_task'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/mels/*$', views.aircraft_mels, name='aircraft_mels'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/assign/*$', views.aircraft_assign_program, name='aircraft_assign'),

    url(r'^(?P<reg>[0-9a-zA-Z]+)/api/tasks/(?P<task_id>[0-9]+)/*$', views.AircraftInspectionTaskView.as_view(), name='api_aircraft_task_list'),

    url(r'^$', views.overview, name='overview'),
]

mxtracking/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('allauth.urls')),
    url(r'^aircraft/', include('home.urls', namespace='home')),
    url(r'^inspectionprogram/', include('inspection.urls', namespace='inspection')),
    url(r'^routeplanning/', include('routeplanning.urls', namespace='routeplanning')),
    url('', include('common.urls')),
]

home/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta

from common.helpers import datetime_now_utc
from inspection.models import *


_bit = lambda x: 2 ** (x-1)
INSPECTION_READABLE = _bit(1)
INSPECTION_WRITABLE = _bit(2)
GANTT_READABLE = _bit(3)
GANTT_WRITABLE = _bit(4)

class UserRole(models.Model):
    name = models.CharField(max_length=50, blank=True)
    access = models.IntegerField(default=0, null=False, blank=False)

    class Meta:
        db_table = 'user_role'

    def __str__(self):
        return self.name

    @property
    def can_read_inspection(self):
        return self.access & INSPECTION_READABLE > 0

    @property
    def can_write_inspection(self):
        return self.access & INSPECTION_WRITABLE > 0

    @property
    def can_read_gantt(self):
        return self.access & GANTT_READABLE > 0

    @property
    def can_write_gantt(self):
        return self.access & GANTT_WRITABLE > 0


class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, related_name='userprofile')
    is_admin = models.BooleanField(default=False, blank=True)

    # Todo: Consider cascading deletion of personal_data
    personal_data = models.OneToOneField('PersonalData', null=True, blank=True)
    role = models.ForeignKey(UserRole, null=True, blank=False)

    @property
    def full_name(self):
        return "%s %s" % (self.personal_data.first_name, self.personal_data.last_name)

    class Meta:
        db_table = 'user_profile'

    def __unicode__(self):
        return self.personal_data.first_name + " " + self.personal_data.last_name


class PersonalData(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    email = models.CharField(max_length=500, blank=True)
    onsip = models.IntegerField(default=0, null=True, blank=True)

    # Todo: Add Profile Image

    class Meta:
        db_table = 'personal_data'
        verbose_name_plural = 'personal data'

    def __unicode__(self):
        return self.first_name + " " + self.last_name


class AircraftType(models.Model):
    type = models.CharField(max_length=50, blank=True)

    class Meta:
        db_table = "aircraft_type"

    def __unicode__(self):
        return self.type


class Aircraft(models.Model):
    reg = models.CharField(max_length=20)
    serial = models.CharField(max_length=20)
    model = models.CharField(max_length=20)
    reported_date = models.DateTimeField(blank=True)

    type = models.ForeignKey(AircraftType, null=True, blank=False)
    inspection_program = models.ForeignKey(InspectionProgram, null=True, blank=False)

    class Meta:
        db_table = 'aircraft'

    def __unicode__(self):
        return self.reg

    # @property
    # def inspections(self):
    #     if self.inspection_program is None:
    #         return []
    #     else:
    #         return self.inspection_program.inspection_set.all().prefetch_related('aircraftinspectionrecord_set')

    # @property
    # def next_inspection_due(self):
    #     inspections = self.inspections
    #     _next_inspection_due = None
    #     _next_inspection_due_date = None
    #     for inspection in inspections:
    #         inspection_records = inspection.aircraftinspectionrecord_set.order_by('-inspection_date').all()
    #         if not inspection_records:
    #             _next_inspection_due = inspection
    #             _next_inspection_due_date = datetime_now_utc()
    #         else:
    #             last_record = inspection_records[0]
    #             next_due_date = last_record.inspection_date + (timedelta(days=inspection.interval) if inspection.interval_unit == 'days' else timedelta(hours=inspection.interval))
    #             if _next_inspection_due_date is None or next_due_date < _next_inspection_due_date:
    #                 _next_inspection_due_date = next_due_date
    #                 _next_inspection_due = inspection

    #     if _next_inspection_due is None:
    #         return (inspections[0], datetime_now_utc()) if inspections else None
    #     return (_next_inspection_due, _next_inspection_due_date)


class Airframe(models.Model):
    total_hours = models.IntegerField(default=0)
    reported_hours = models.IntegerField(default=0)
    reported_landings = models.IntegerField(default=0)
    last_inspection_time = models.DateTimeField(null=True, blank=True)

    aircraft = models.OneToOneField(Aircraft, null=True, blank=False)

    class Meta:
        db_table = 'airframe'

    @property
    def time_between_inspections(self):
        return 120

    @property
    def next_inspection_time(self):
        return self.last_inspection_time + timedelta(days=75)


class Engine(models.Model):
    date = models.DateField(blank=True)
    engine_hours = models.IntegerField(default=0, null=True, blank=True)
    engine_cycles = models.IntegerField(default=0, null=True, blank=True)
    last_hot_section_time = models.DateTimeField(blank=True)
    last_overhaul_time = models.DateTimeField(blank=True)
    tbo = models.IntegerField(default=0, null=True, blank=True)

    aircraft = models.ForeignKey(Aircraft, null=True, blank=False)

    class Meta:
        db_table = 'engine'

    @property
    def next_inspection_time(self):
        return self.last_hot_section_time + timedelta(days=90)


class Propeller(models.Model):
    last_inspection_time = models.DateTimeField(blank=True)

    aircraft = models.ForeignKey(Aircraft, null=True, blank=False)

    class Meta:
        db_table = 'propeller'

    @property
    def next_inspection_time(self):
        return self.last_inspection_time + timedelta(days=90)


class InspectionComponentSubItem(models.Model):
    TYPE_MOS = 1
    TYPE_HRS = 2
    TYPE_AFL = 3
    TYPE_STRINGS = ('', 'MOS', 'HRS', 'AFL')
    TYPE_CHOICES = (
        (TYPE_MOS, TYPE_STRINGS[TYPE_MOS]),
        (TYPE_HRS, TYPE_STRINGS[TYPE_HRS]),
        (TYPE_AFL, TYPE_STRINGS[TYPE_AFL]),
    )

    type = models.IntegerField(default=1, choices=TYPE_CHOICES)
    interval = models.IntegerField(null=False, blank=False)
    CW = models.CharField(max_length=50, null=False, blank=True, default='')
    TSX_adj = models.CharField(max_length=50, null=False, blank=True, default='')
    max_limit = models.CharField(max_length=50, null=False, blank=True, default='')

    aircraft = models.ForeignKey(Aircraft, null=True, blank=False)
    inspection_component = models.ForeignKey(InspectionComponent, null=True, blank=False)

    class Meta:
        db_table = 'inspection_component_sub_item'

    def __unicode__(self):
        return InspectionComponentSubItem.TYPE_STRINGS[self.type]

inspection/models.py
from __future__ import unicode_literals

from django.db import models

from common.helpers import *


class InspectionTask(models.Model):
    TARGET_AIRCRAFT = 1
    TARGET_AIRFRAME = 2
    TARGET_PROPELLER = 3
    TARGET_ENGINE = 4
    TARGET_STRINGS = ('', 'Aircraft', 'Airframe', 'Propeller', 'Engine')
    INSPECTION_TARGET_CHOICES = (
        (TARGET_AIRCRAFT, TARGET_STRINGS[TARGET_AIRCRAFT]),
        (TARGET_AIRFRAME, TARGET_STRINGS[TARGET_AIRFRAME]),
        (TARGET_PROPELLER, TARGET_STRINGS[TARGET_PROPELLER]),
        (TARGET_ENGINE, TARGET_STRINGS[TARGET_ENGINE]),
    )

    number = models.IntegerField(null=False, blank=False)
    name = models.CharField(max_length=100, blank=False)

    target = models.IntegerField(default=1, choices=INSPECTION_TARGET_CHOICES)

    class Meta:
        db_table = 'inspection_task'

    def __unicode__(self):
        return ndigits(self.number, 2) + ' - ' + self.name

    @property
    def target_name(self):
        target_choice_item = None
        for item in InspectionTask.INSPECTION_TARGET_CHOICES:
            if item[0] == self.target:
                target_choice_item = item
                break
        return target_choice_item[1] if target_choice_item else ''


class InspectionProgram(models.Model):
    name = models.CharField(max_length=100, blank=False)

    inspection_tasks = models.ManyToManyField(InspectionTask)

    class Meta:
        db_table = 'inspection_program'

    def __unicode__(self):
        return self.name


class InspectionComponent(models.Model):
    pn = models.CharField(max_length=30, blank=False)
    sn = models.CharField(max_length=30, blank=False)
    name = models.CharField(max_length=100, blank=False)

    inspection_task = models.ForeignKey('InspectionTask', null=True, blank=False)

    class Meta:
        db_table = 'inspection_component'

    def __unicode__(self):
        return self.name

home/forms.py
from django import forms

from inspection.models import InspectionProgram


class AssignInspectionProgramForm(forms.Form):
    inspection_program = forms.ModelChoiceField(
        queryset=InspectionProgram.objects.all(),
        label='Inspection Program',
        empty_label='(Not assigned)',
        required=True
    )

    class Meta:
        fields = ('inspection_program',)

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, JsonResponse
from django.views.generic import TemplateView
from datetime import timedelta

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated

from home.models import *
from home.forms import *
from home.serializers import *
from common.helpers import *
from common.decorators import *


@login_required
@inspection_readable_required
def overview(request):
    aircrafts = Aircraft.objects.all().select_related('airframe')

    past_due_count = 0
    threshold_count = 0
    coming_due_count = 0

    # for aircraft in aircrafts:
    #     if aircraft.next_inspection_due is not None:
    #         next_due_date = aircraft.next_inspection_due[1]
    #         if is_past_due(next_due_date):
    #             past_due_count += 1
    #         elif is_within_threshold(next_due_date):
    #             threshold_count += 1
    #         else:
    #             coming_due_count += 1

    context = {
        'aircrafts': aircrafts,
        'past_due_count': past_due_count,
        'threshold_count': threshold_count,
        'coming_due_count': coming_due_count,
    }
    return render(request, 'overview.html', context)

@login_required
@inspection_readable_required
def aircraft_details(request, reg=''):
    aircraft = get_object_or_404(Aircraft.objects.select_related('airframe'), reg=reg)

    context = {
        'aircraft': aircraft,
    }
    return render(request, 'details.html', context)

@login_required
@inspection_readable_required
def aircraft_task_list(request, reg=''):
    aircraft = get_object_or_404(Aircraft.objects.select_related('inspection_program'), reg=reg)
    inspection_program = aircraft.inspection_program
    inspection_tasks = inspection_program.inspection_tasks.all() if inspection_program else []

    context = {
        'aircraft': aircraft,
        'inspection_program': inspection_program,
        'inspection_tasks': inspection_tasks,
    }
    return render(request, 'task_list.html', context)

@login_required
@inspection_readable_required
def aircraft_task(request, reg='', task_id=None):
    aircraft = get_object_or_404(Aircraft.objects.select_related('inspection_program'), reg=reg)
    inspection_task = get_object_or_404(InspectionTask, pk=task_id)

    context = {
        'aircraft': aircraft,
        'inspection_task': inspection_task,
        'inspection_task_name': str(inspection_task),
    }
    return render(request, 'task.html', context)

@login_required
@inspection_readable_required
def aircraft_mels(request, reg=''):
    aircraft = get_object_or_404(Aircraft, reg=reg)

    context = {
        'aircraft': aircraft,
    }
    return render(request, 'mels.html', context)

# maybe temporary
@login_required
@inspection_readable_required
def aircraft_assign_program(request, reg=''):
    aircraft = get_object_or_404(Aircraft, reg=reg)

    form = AssignInspectionProgramForm(request.POST or {
        'inspection_program': aircraft.inspection_program
    })
    if request.method == 'POST':
        if not can_write_inspection(request.user):
            return HttpResponseForbidden()
        if form.is_valid():
            inspection_program = form.cleaned_data.get('inspection_program')

            aircraft.inspection_program = inspection_program
            aircraft.save()

            for inspection_task in inspection_program.inspection_tasks.order_by('id'):
                for inspection_component in inspection_task.inspectioncomponent_set.order_by('id'):
                    for ic_type in InspectionComponentSubItem.TYPE_CHOICES:
                        type = ic_type[0]
                        try:
                            inspection_component_sub_item = InspectionComponentSubItem.objects.get(
                                type=type,
                                aircraft=aircraft,
                                inspection_component=inspection_component
                            )
                        except:
                            inspection_component_sub_item = InspectionComponentSubItem(
                                type=type,
                                aircraft=aircraft,
                                inspection_component=inspection_component,
                                interval=0
                            )
                            inspection_component_sub_item.save()

            return redirect('home:aircraft_task_list', reg=aircraft.reg)

    context = {
        'aircraft': aircraft,
        'form': form,
    }
    return render(request, 'assign_inspection_program.html', context)


class AircraftInspectionTaskView(APIView):
    authentication_classes = (SessionAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get(self, request, reg='', task_id=None):
        aircraft = get_object_or_404(Aircraft, reg=reg)
        inspection_task = get_object_or_404(InspectionTask, pk=task_id)

        task_serializer = InspectionTaskSerializer(inspection_task)
        task_data = task_serializer.data

        components_serializer = InspectionComponentSerializer(inspection_task.inspectioncomponent_set.order_by('id'), many=True)
        components_data = components_serializer.data

        return Response({
            'task': task_data,
            'components': components_data,
        })

    def post(self, request, reg='', task_id=None):
        aircraft = get_object_or_404(Aircraft, reg=reg)
        inspection_task = get_object_or_404(InspectionTask, pk=task_id)

        response = {
            'success': False,
        }

        component_id = request.data.get('component_id')
        sub_item_id = request.data.get('sub_item_id')
        field = request.data.get('field')
        value = request.data.get('value')

        try:
            inspection_component = inspection_task.inspectioncomponent_set.get(pk=component_id)
        except Exception as e:
            response['message'] = 'Invalid task component id'
            return Response(response)

        try:
            inspection_component_sub_item = inspection_component.inspectioncomponentsubitem_set.get(pk=sub_item_id)
        except Exception as e:
            response['message'] = 'Invalid task component sub item id'
            return Response(response)

        try:
            InspectionComponentSubItem._meta.get_field(field)
            setattr(inspection_component_sub_item, field, value)
            inspection_component_sub_item.save()
        except Exception as e:
            response['message'] = 'Failed to save data'
            return Response(response)

        response['success'] = True
        return Response(response)

home/templates/aircraft_details.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block head_title %}Aircraft Details{% endblock %}

{% block page_title %}
    Aircraft Details
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'home:overview' %}">Overview</a>
        </li>
        <li class="active">
            <span>{{ aircraft.reg }} Aircraft Details</span>
        </li>
    </ol>
{% endblock %}

{% block content %}
    {% include 'partial/aircraft_details.html' %}
{% endblock %}

home/templates/assign_inspection_program.html
{% extends "layout.html" %}
{% load staticfiles %}
{% load addclass %}

{% block head_title %}Assign Inspection Program{% endblock %}

{% block page_title %}
    Assign Inspection Program
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'home:overview' %}">Overview</a>
        </li>
        <li>
            <a href="{% url 'home:aircraft_details' reg=aircraft.reg %}">{{ aircraft.reg }}</a>
        </li>
        <li class="active">
            <span>Assign Inspection Program</span>
        </li>
    </ol>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12 col-xs-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h3>Assign Inspection Program</h3>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="{{ field.name }}">{{ field.label }}</label>
                                <div class="col-sm-8">
                                    {{ field.errors }}
                                    {{ field | addclass:'form-control' }}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="text-right m-t-lg">
                            <button class="btn btn-primary" type="submit">Assign</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block pagejs %}
    <script>
        $(document).ready(function(){
            $('.select2').select2();
        });
    </script>
{% endblock %}

home/templates/details.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block head_title %}Aircraft Details{% endblock %}

{% block page_title %}
    Aircraft Details
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'home:overview' %}">Overview</a>
        </li>
        <li class="active">
            <span>{{ aircraft.reg }} Aircraft Details</span>
        </li>
    </ol>
{% endblock %}

{% block content %}
    {% include 'partial/aircraft_details.html' %}
{% endblock %}

home/templates/mels.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block head_title %}Aircraft {{ aircraft.reg }} MELs{% endblock %}

{% block page_title %}
    Aircraft {{ aircraft.reg }} MELs
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'home:overview' %}">Overview</a>
        </li>
        <li>
            <a href="{% url 'home:aircraft_details' reg=aircraft.reg %}">{{ aircraft.reg }}</a>
        </li>
        <li class="active">
            <span>MELs</span>
        </li>
    </ol>
{% endblock %}

{% block content %}
    <div class="ibox">
        <div class="ibox-title">
            <h3>MELs</h3>
        </div>
        <div class="ibox-content">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Reg #</th>
                        <th>Date Logged</th>
                        <th>Date Closed</th>
                        <th>WO Number</th>
                        <th>Category</th>
                        <th>Status</th>
                        <th>C/W Date</th>
                        <th>Unit</th>
                        <th>Interval</th>
                        <th>Logbook Times</th>
                        <th>Due (Ext)</th>
                        <th>Tracked</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="12">
                            <strong class="uppercase">
                                170208-3 L/H O/B Aft Cowling Attach Bracket Cracked
                            </strong>
                            <div class="pull-right">Service ATA:71</div>
                        </td>
                    </tr>
                    <tr>
                        <td>N165TG</td>
                        <td>08-FEB-17</td>
                        <td></td>
                        <td>N165TGP2-2/6/17</td>
                        <td class="uppercase">Non-Deferred</td>
                        <td class="uppercase">Open</td>
                        <td></td>
                        <td>Days</td>
                        <td></td>
                        <td>08-FEB-17</td>
                        <td>08-FEB-17</td>
                        <td>No</td>
                    </tr>
                    <tr>
                        <td colspan="12">
                            <strong class="uppercase">
                                170208-3 L/H O/B Aft Cowling Attach Bracket Cracked
                            </strong>
                            <div class="pull-right">Service ATA:71</div>
                        </td>
                    </tr>
                    <tr>
                        <td>N165TG</td>
                        <td>08-FEB-17</td>
                        <td></td>
                        <td>N165TGP2-2/6/17</td>
                        <td class="uppercase">Non-Deferred</td>
                        <td class="uppercase">Open</td>
                        <td></td>
                        <td>Days</td>
                        <td></td>
                        <td>08-FEB-17</td>
                        <td>08-FEB-17</td>
                        <td>No</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

home/templates/task.html
{% extends "layout.html" %}
{% load staticfiles %}
{% load formatter %}

{% block head_title %}Aircraft {{ aircraft.reg }}: {{ inspection_task_name }}{% endblock %}

{% block page_title %}
    Aircraft {{ aircraft.reg }}: {{ inspection_task_name }}
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'home:overview' %}">Overview</a>
        </li>
        <li>
            <a href="{% url 'home:aircraft_details' reg=aircraft.reg %}">{{ aircraft.reg }}</a>
        </li>
        <li>
            <a href="{% url 'home:aircraft_task_list' reg=aircraft.reg %}">Task List</a>
        </li>
        <li class="active">
            <span>{{ inspection_task_name }}</span>
        </li>
    </ol>
{% endblock %}

{% block content %}
    <div class="ibox">
        <div class="ibox-title">
            <h3>{{ inspection_task_name }}</h3>
        </div>
        <div class="ibox-content">
            <div id="task-table">
            </div>
        </div>
    </div>
{% endblock %}

{% block pagejs %}
    <script type="text/javascript">
        window.initTaskTable('#task-table', {
            aircraftReg: '{{ aircraft.reg }}',
            inspectionTaskId: {{ inspection_task.id }},
            loadApiUrl: "{% url 'home:api_aircraft_task_list' reg=aircraft.reg task_id=inspection_task.id %}",
            updateCellApiUrl: "{% url 'home:api_aircraft_task_list' reg=aircraft.reg task_id=inspection_task.id %}",
        });
    </script>
{% endblock %}

home/templates/task_list.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block head_title %}Aircraft {{ aircraft.reg }} Task List{% endblock %}

{% block page_title %}
    Aircraft {{ aircraft.reg }} Task List
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'home:overview' %}">Overview</a>
        </li>
        <li>
            <a href="{% url 'home:aircraft_details' reg=aircraft.reg %}">{{ aircraft.reg }}</a>
        </li>
        <li class="active">
            <span>Task List</span>
        </li>
    </ol>
{% endblock %}

{% block content %}
    <div class="ibox">
        <div class="ibox-title">
            <h3>Task List</h3>
        </div>
        <div class="ibox-content">
            {% for inspection_program in inspection_programs %}
                <h5>{{ inspection_program.number }} - {{ inspection_program.name }} ({{ inspection_program.inspectiontask_set.count }})</h5>
            {% endfor %}
        </div>
    </div>
{% endblock %}

home/templates/test.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block head_title %}Test{% endblock %}

{% block page_title %}
    Home
{% endblock %}

{% block breadcrumb %}
    Home
{% endblock %}

{% block content %}
    <h1>Welcome!</h1>
{% endblock %}