home/urls.py
from django.conf.urls import url

from home import views


urlpatterns = [
    url(r'^(?P<reg>[0-9a-zA-Z]+)/*$', views.aircraft_details, name='aircraft_details'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/tasks/*$', views.aircraft_task_list, name='aircraft_task_list'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/tasks/(?P<task_id>[0-9]+)/*$', views.aircraft_task, name='aircraft_task'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/mels/*$', views.aircraft_mels, name='aircraft_mels'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/assign/*$', views.aircraft_assign_program, name='aircraft_assign'),

    url(r'^(?P<reg>[0-9a-zA-Z]+)/api/tasks/(?P<task_id>[0-9]+)/*$', views.AircraftInspectionTaskView.as_view(), name='api_aircraft_task_list'),

    url(r'^$', views.overview, name='overview'),
]

mxtracking/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('allauth.urls')),
    url(r'^aircraft/', include('home.urls', namespace='home')),
    url(r'^inspectionprogram/', include('inspection.urls', namespace='inspection')),
    url(r'^routeplanning/', include('routeplanning.urls', namespace='routeplanning')),
    url('', include('common.urls')),
]

home/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta

from common.helpers import datetime_now_utc
from inspection.models import *


_bit = lambda x: 2 ** (x-1)
INSPECTION_READABLE = _bit(1)
INSPECTION_WRITABLE = _bit(2)
GANTT_READABLE = _bit(3)
GANTT_WRITABLE = _bit(4)

class UserRole(models.Model):
    name = models.CharField(max_length=50, blank=True)
    access = models.IntegerField(default=0, null=False, blank=False)

    class Meta:
        db_table = 'user_role'

    def __str__(self):
        return self.name

    @property
    def can_read_inspection(self):
        return self.access & INSPECTION_READABLE > 0

    @property
    def can_write_inspection(self):
        return self.access & INSPECTION_WRITABLE > 0

    @property
    def can_read_gantt(self):
        return self.access & GANTT_READABLE > 0

    @property
    def can_write_gantt(self):
        return self.access & GANTT_WRITABLE > 0


class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, related_name='userprofile')
    is_admin = models.BooleanField(default=False, blank=True)

    # Todo: Consider cascading deletion of personal_data
    personal_data = models.OneToOneField('PersonalData', null=True, blank=True)
    role = models.ForeignKey(UserRole, null=True, blank=False)

    @property
    def full_name(self):
        return "%s %s" % (self.personal_data.first_name, self.personal_data.last_name)

    class Meta:
        db_table = 'user_profile'

    def __unicode__(self):
        return self.personal_data.first_name + " " + self.personal_data.last_name


class PersonalData(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    email = models.CharField(max_length=500, blank=True)
    onsip = models.IntegerField(default=0, null=True, blank=True)

    # Todo: Add Profile Image

    class Meta:
        db_table = 'personal_data'
        verbose_name_plural = 'personal data'

    def __unicode__(self):
        return self.first_name + " " + self.last_name


class AircraftType(models.Model):
    type = models.CharField(max_length=50, blank=True)

    class Meta:
        db_table = "aircraft_type"

    def __unicode__(self):
        return self.type


class Aircraft(models.Model):
    reg = models.CharField(max_length=20)
    serial = models.CharField(max_length=20)
    model = models.CharField(max_length=20)
    reported_date = models.DateTimeField(blank=True)

    type = models.ForeignKey(AircraftType, null=True, blank=False)
    inspection_program = models.ForeignKey(InspectionProgram, null=True, blank=False)

    class Meta:
        db_table = 'aircraft'

    def __unicode__(self):
        return self.reg

    # @property
    # def inspections(self):
    #     if self.inspection_program is None:
    #         return []
    #     else:
    #         return self.inspection_program.inspection_set.all().prefetch_related('aircraftinspectionrecord_set')

    # @property
    # def next_inspection_due(self):
    #     inspections = self.inspections
    #     _next_inspection_due = None
    #     _next_inspection_due_date = None
    #     for inspection in inspections:
    #         inspection_records = inspection.aircraftinspectionrecord_set.order_by('-inspection_date').all()
    #         if not inspection_records:
    #             _next_inspection_due = inspection
    #             _next_inspection_due_date = datetime_now_utc()
    #         else:
    #             last_record = inspection_records[0]
    #             next_due_date = last_record.inspection_date + (timedelta(days=inspection.interval) if inspection.interval_unit == 'days' else timedelta(hours=inspection.interval))
    #             if _next_inspection_due_date is None or next_due_date < _next_inspection_due_date:
    #                 _next_inspection_due_date = next_due_date
    #                 _next_inspection_due = inspection

    #     if _next_inspection_due is None:
    #         return (inspections[0], datetime_now_utc()) if inspections else None
    #     return (_next_inspection_due, _next_inspection_due_date)


class Airframe(models.Model):
    total_hours = models.IntegerField(default=0)
    reported_hours = models.IntegerField(default=0)
    reported_landings = models.IntegerField(default=0)
    last_inspection_time = models.DateTimeField(null=True, blank=True)

    aircraft = models.OneToOneField(Aircraft, null=True, blank=False)

    class Meta:
        db_table = 'airframe'

    @property
    def time_between_inspections(self):
        return 120

    @property
    def next_inspection_time(self):
        return self.last_inspection_time + timedelta(days=75)


class Engine(models.Model):
    date = models.DateField(blank=True)
    engine_hours = models.IntegerField(default=0, null=True, blank=True)
    engine_cycles = models.IntegerField(default=0, null=True, blank=True)
    last_hot_section_time = models.DateTimeField(blank=True)
    last_overhaul_time = models.DateTimeField(blank=True)
    tbo = models.IntegerField(default=0, null=True, blank=True)

    aircraft = models.ForeignKey(Aircraft, null=True, blank=False)

    class Meta:
        db_table = 'engine'

    @property
    def next_inspection_time(self):
        return self.last_hot_section_time + timedelta(days=90)


class Propeller(models.Model):
    last_inspection_time = models.DateTimeField(blank=True)

    aircraft = models.ForeignKey(Aircraft, null=True, blank=False)

    class Meta:
        db_table = 'propeller'

    @property
    def next_inspection_time(self):
        return self.last_inspection_time + timedelta(days=90)


class InspectionComponentSubItem(models.Model):
    TYPE_MOS = 1
    TYPE_HRS = 2
    TYPE_AFL = 3
    TYPE_STRINGS = ('', 'MOS', 'HRS', 'AFL')
    TYPE_CHOICES = (
        (TYPE_MOS, TYPE_STRINGS[TYPE_MOS]),
        (TYPE_HRS, TYPE_STRINGS[TYPE_HRS]),
        (TYPE_AFL, TYPE_STRINGS[TYPE_AFL]),
    )

    type = models.IntegerField(default=1, choices=TYPE_CHOICES)
    interval = models.IntegerField(null=False, blank=False)
    CW = models.CharField(max_length=50, null=False, blank=True, default='')
    TSX_adj = models.CharField(max_length=50, null=False, blank=True, default='')
    max_limit = models.CharField(max_length=50, null=False, blank=True, default='')

    aircraft = models.ForeignKey(Aircraft, null=True, blank=False)
    inspection_component = models.ForeignKey(InspectionComponent, null=True, blank=False)

    class Meta:
        db_table = 'inspection_component_sub_item'

    def __unicode__(self):
        return InspectionComponentSubItem.TYPE_STRINGS[self.type]

home/forms.py
from django import forms

from inspection.models import InspectionProgram


class AssignInspectionProgramForm(forms.Form):
    inspection_program = forms.ModelChoiceField(
        queryset=InspectionProgram.objects.all(),
        label='Inspection Program',
        empty_label='(Not assigned)',
        required=True
    )

    class Meta:
        fields = ('inspection_program',)

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, JsonResponse
from django.views.generic import TemplateView
from datetime import timedelta

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated

from home.models import *
from home.forms import *
from home.serializers import *
from common.helpers import *
from common.decorators import *


@login_required
@inspection_readable_required
def overview(request):
    aircrafts = Aircraft.objects.all().select_related('airframe')

    past_due_count = 0
    threshold_count = 0
    coming_due_count = 0

    # for aircraft in aircrafts:
    #     if aircraft.next_inspection_due is not None:
    #         next_due_date = aircraft.next_inspection_due[1]
    #         if is_past_due(next_due_date):
    #             past_due_count += 1
    #         elif is_within_threshold(next_due_date):
    #             threshold_count += 1
    #         else:
    #             coming_due_count += 1

    context = {
        'aircrafts': aircrafts,
        'past_due_count': past_due_count,
        'threshold_count': threshold_count,
        'coming_due_count': coming_due_count,
    }
    return render(request, 'overview.html', context)

@login_required
@inspection_readable_required
def aircraft_details(request, reg=''):
    aircraft = get_object_or_404(Aircraft.objects.select_related('airframe'), reg=reg)

    context = {
        'aircraft': aircraft,
    }
    return render(request, 'details.html', context)

@login_required
@inspection_readable_required
def aircraft_task_list(request, reg=''):
    aircraft = get_object_or_404(Aircraft.objects.select_related('inspection_program'), reg=reg)
    inspection_program = aircraft.inspection_program
    inspection_tasks = inspection_program.inspection_tasks.all() if inspection_program else []

    context = {
        'aircraft': aircraft,
        'inspection_program': inspection_program,
        'inspection_tasks': inspection_tasks,
    }
    return render(request, 'task_list.html', context)

@login_required
@inspection_readable_required
def aircraft_task(request, reg='', task_id=None):
    aircraft = get_object_or_404(Aircraft.objects.select_related('inspection_program'), reg=reg)
    inspection_task = get_object_or_404(InspectionTask, pk=task_id)

    context = {
        'aircraft': aircraft,
        'inspection_task': inspection_task,
        'inspection_task_name': str(inspection_task),
    }
    return render(request, 'task.html', context)

@login_required
@inspection_readable_required
def aircraft_mels(request, reg=''):
    aircraft = get_object_or_404(Aircraft, reg=reg)

    context = {
        'aircraft': aircraft,
    }
    return render(request, 'mels.html', context)

# maybe temporary
@login_required
@inspection_readable_required
def aircraft_assign_program(request, reg=''):
    aircraft = get_object_or_404(Aircraft, reg=reg)

    form = AssignInspectionProgramForm(request.POST or {
        'inspection_program': aircraft.inspection_program
    })
    if request.method == 'POST':
        if not can_write_inspection(request.user):
            return HttpResponseForbidden()
        if form.is_valid():
            inspection_program = form.cleaned_data.get('inspection_program')

            aircraft.inspection_program = inspection_program
            aircraft.save()

            for inspection_task in inspection_program.inspection_tasks.order_by('id'):
                for inspection_component in inspection_task.inspectioncomponent_set.order_by('id'):
                    for ic_type in InspectionComponentSubItem.TYPE_CHOICES:
                        type = ic_type[0]
                        try:
                            inspection_component_sub_item = InspectionComponentSubItem.objects.get(
                                type=type,
                                aircraft=aircraft,
                                inspection_component=inspection_component
                            )
                        except:
                            inspection_component_sub_item = InspectionComponentSubItem(
                                type=type,
                                aircraft=aircraft,
                                inspection_component=inspection_component,
                                interval=0
                            )
                            inspection_component_sub_item.save()

            return redirect('home:aircraft_task_list', reg=aircraft.reg)

    context = {
        'aircraft': aircraft,
        'form': form,
    }
    return render(request, 'assign_inspection_program.html', context)


class AircraftInspectionTaskView(APIView):
    authentication_classes = (SessionAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get(self, request, reg='', task_id=None):
        aircraft = get_object_or_404(Aircraft, reg=reg)
        inspection_task = get_object_or_404(InspectionTask, pk=task_id)

        task_serializer = InspectionTaskSerializer(inspection_task)
        task_data = task_serializer.data

        components_serializer = InspectionComponentSerializer(inspection_task.inspectioncomponent_set.order_by('id'), many=True)
        components_data = components_serializer.data

        return Response({
            'task': task_data,
            'components': components_data,
        })

    def post(self, request, reg='', task_id=None):
        aircraft = get_object_or_404(Aircraft, reg=reg)
        inspection_task = get_object_or_404(InspectionTask, pk=task_id)

        response = {
            'success': False,
        }

        component_id = request.data.get('component_id')
        sub_item_id = request.data.get('sub_item_id')
        field = request.data.get('field')
        value = request.data.get('value')

        try:
            inspection_component = inspection_task.inspectioncomponent_set.get(pk=component_id)
        except Exception as e:
            response['message'] = 'Invalid task component id'
            return Response(response)

        try:
            inspection_component_sub_item = inspection_component.inspectioncomponentsubitem_set.get(pk=sub_item_id)
        except Exception as e:
            response['message'] = 'Invalid task component sub item id'
            return Response(response)

        try:
            InspectionComponentSubItem._meta.get_field(field)
            setattr(inspection_component_sub_item, field, value)
            inspection_component_sub_item.save()
        except Exception as e:
            response['message'] = 'Failed to save data'
            return Response(response)

        response['success'] = True
        return Response(response)

home/templates/partial/aircraft_details.html
{% load duestatus %}
<div class="ibox">
    <div class="ibox-title">
        <h3>Aircraft Details</h3>
    </div>
    <div class="ibox-content">
        <table>
            <tr>
                <td>Reg #</td>
                <td>{{ aircraft.reg }}</td>
            </tr>
            <tr>
                <td>Serial #</td>
                <td>{{ aircraft.serial }}</td>
            </tr>
            <tr>
                <td>Model #</td>
                <td>{{ aircraft.model }}</td>
            </tr>
            <tr>
                <td>MX Program:&nbsp;&nbsp;</td>
                <td>
                    {% if aircraft.inspection_program %}
                        {{ aircraft.inspection_program.name }}
                    {% else %}
                        Inspection Program Unassigned. <a href="{% url 'home:aircraft_assign' reg=aircraft.reg %}">Assign</a>
                    {% endif %}
                </td>
            </tr>
        </table>
        <div class="btn-group m-t-sm">
            <a class="btn btn-white" href="{% url 'home:aircraft_mels' reg=aircraft.reg %}">MELs</a>
            <a class="btn btn-white" href="{% url 'home:aircraft_task_list' reg=aircraft.reg %}">Task List</a>
            <button class="btn btn-white" type="button">Next Item Due</button>
        </div>
    </div>
</div>
<div class="ibox">
    <div class="ibox-title">
        <h3>Overview</h3>
    </div>
    <div class="ibox-content">
        <table class="table table-stripped">
            <thead>
                <tr>
                    <th>Reported Date</th>
                    <th>Reported Hours</th>
                    <th>Reported Landings</th>
                    <th>Next Item Due</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ aircraft.reported_date | date:"d-M-Y" }}</td>
                    <td>{{ aircraft.airframe.reported_hours }}</td>
                    <td>{{ aircraft.airframe.reported_landings }}</td>
                    <td>{{ aircraft.airframe.next_inspection_time | date:"d-M-Y" }}</td>
                    <td>{{ aircraft.airframe.next_inspection_time | duestatus }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="ibox">
    <div class="ibox-title">
        <h3>Airframe</h3>
    </div>
    <div class="ibox-content">
        <table class="table table-stripped">
            <thead>
                <tr>
                    <th>Airframe Total Hours</th>
                    <th>Reported Hours</th>
                    <th>Landings</th>
                    <th>Last Inspection Time</th>
                    <th>Next Inspection Time</th>
                    <th>Time Between Inspections</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ aircraft.airframe.total_hours }}</td>
                    <td>{{ aircraft.airframe.reported_hours }}</td>
                    <td>{{ aircraft.airframe.reported_landings }}</td>
                    <td>{{ aircraft.airframe.last_inspection_time | date:"d-M-Y" }}</td>
                    <td>{{ aircraft.airframe.next_inspection_time | date:"d-M-Y" }}</td>
                    <td>{{ aircraft.airframe.time_between_inspections }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="ibox">
    <div class="ibox-title">
        <h3>Engine</h3>
    </div>
    <div class="ibox-content">
        <table class="table table-stripped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Engine Hours</th>
                    <th>Engine Cycles</th>
                    <th>Hot Section Due Time</th>
                    <th>Time of Last Hot Section</th>
                    <th>Time of Last Overhaul</th>
                    <th>Overhaul Due Time</th>
                    <th>TBO</th>
                </tr>
            </thead>
            <tbody>
                {% for engine in aircraft.engine_set.all %}
                    <tr>
                        <td>{{ engine.date | date:"d-M-Y" }}</td>
                        <td>{{ engine.engine_hours }}</td>
                        <td>{{ engine.engine_cycles }}</td>
                        <td>{{ engine.last_hot_section_time | date:"d-M-Y" }}</td>
                        <td>{{ engine.last_hot_section_time | date:"d-M-Y" }}</td>
                        <td>{{ engine.last_overhaul_time | date:"d-M-Y" }}</td>
                        <td>{{ engine.next_inspection_time | date:"d-M-Y" }}</td>
                        <td>{{ engine.tbo }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="ibox">
    <div class="ibox-title">
        <h3>Propeller</h3>
    </div>
    <div class="ibox-content">
        <table class="table table-stripped">
            <thead>
                <tr>
                    <th>Time of Last Inspection</th>
                    <th>Next Inspection Due Date</th>
                </tr>
            </thead>
            <tbody>
                {% for propeller in aircraft.propeller_set.all %}
                    <tr>
                        <td>{{ propeller.last_inspection_time | date:"d-M-Y" }}</td>
                        <td>{{ propeller.next_inspection_time | date:"d-M-Y" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>