home/urls.py
from django.conf.urls import url

from home import views


urlpatterns = [
    url(r'^(?P<reg>[0-9a-zA-Z]+)/*$', views.aircraft_details, name='aircraft_details'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/tasks/*$', views.aircraft_task_list, name='aircraft_task_list'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/tasks/(?P<task_id>[0-9]+)/*$', views.aircraft_task, name='aircraft_task'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/mels/*$', views.aircraft_mels, name='aircraft_mels'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/assign/*$', views.aircraft_assign_program, name='aircraft_assign'),

    url(r'^(?P<reg>[0-9a-zA-Z]+)/api/tasks/(?P<task_id>[0-9]+)/*$', views.AircraftInspectionTaskView.as_view(), name='api_aircraft_task_list'),

    url(r'^$', views.overview, name='overview'),
]

inspection/urls.py
from django.conf.urls import url

from inspection import views


urlpatterns = [
    url(r'^create/*$', views.create_inspection_program, name='create_inspection_program'),
    url(r'^(?P<program_id>[0-9a-zA-Z]+)/*$', views.inspection_program_details, name='inspection_program_details'),
    url(r'^(?P<program_id>[0-9a-zA-Z]+)/task/add/*$', views.add_inspection_task, name='add_inspection_task'),
    url(r'^$', views.index, name='index'),
]

mxtracking/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('allauth.urls')),
    url(r'^aircraft/', include('home.urls', namespace='home')),
    url(r'^inspectionprogram/', include('inspection.urls', namespace='inspection')),
    url(r'^routeplanning/', include('routeplanning.urls', namespace='routeplanning')),
    url('', include('common.urls')),
]

routeplanning/urls.py
from django.conf.urls import url

from routeplanning.views import api_views
from routeplanning.views import page_views


urlpatterns = [
    url(r'^tail/add/*$', page_views.AddTailView.as_view(), name='add_tail'),
    url(r'^tail/(?P<tail_id>[0-9]+)/*$', page_views.EditTailView.as_view(), name='edit_tail'),
    url(r'^tail/(?P<tail_id>[0-9]+)/revision/(?P<revision_id>[0-9]+)/comingdue/*$',
        page_views.ComingDueView.as_view(), name='coming_due'),

    url(r'^line/add/*$', page_views.AddLineView.as_view(), name='add_line'),
    url(r'^line/(?P<line_id>[0-9]+)/*$', page_views.EditLineView.as_view(), name='edit_line'),

    url(r'^flights/*$', page_views.FlightListView.as_view(), name='flights'),
    url(r'^flights/add/*$', page_views.AddFlightView.as_view(), name='add_flight'),
    url(r'^flights/(?P<flight_id>[0-9]+)/*$', page_views.EditFlightView.as_view(), name='edit_flight'),
    url(r'^flights/delete/*$', page_views.DeleteFlightView.as_view(), name='delete_flights'),

    url(r'^$', page_views.IndexView.as_view(), name='index'),
    url(r'^view-gantt/*$', page_views.CurrentPublishedGanttView.as_view(), name='view_current_published_gantt'),

    url(r'^api/loaddata/*$', api_views.LoadDataView.as_view(), name='api_load_data'),
    url(r'^api/line/(?P<line_id>[0-9]+)/delete/*$', api_views.DeleteLineView.as_view(), name='delete_line'),
    url(r'^api/tail/(?P<tail_id>[0-9]+)/delete/*$', api_views.DeleteTailView.as_view(), name='delete_tail'),
    url(r'^api/tail/assignflight/*$', api_views.AssignFlightView.as_view(), name='api_assign_flight'),
    url(r'^api/tail/assignstatus/*$', api_views.AssignStatusView.as_view(), name='api_assign_status'),
    url(r'^api/tail/hobbs/*$', api_views.SaveHobbsView.as_view(), name='api_save_hobbs'),
    url(r'^api/tail/comingduelist/*$', api_views.ComingDueListView.as_view(), name='api_coming_due_list'),
    url(r'^api/assignment/move/*$', api_views.MoveAssignmentView.as_view(), name='api_move_assignment'),
    url(r'^api/assignment/remove/*$', api_views.RemoveAssignmentView.as_view(), name='api_remove_assignment'),
    url(r'^api/assignment/resize/*$', api_views.ResizeAssignmentView.as_view(), name='api_resize_assignment'),
    url(r'^api/flight/uploadcsv/*$', api_views.UploadCSVView.as_view(), name='api_upload_csv'),
    url(r'^api/flight/getpage/*$', api_views.FlightListView.as_view(), name='api_flight_get_page'),
    url(r'^api/hobbs/(?P<hobbs_id>[0-9]+)/*$', api_views.HobbsView.as_view(), name='api_hobbs'),
    url(r'^api/revision/publish/*$', api_views.PublishRevisionView.as_view(), name='api_publish_revision'),
    url(r'^api/revision/clear/*$', api_views.ClearRevisionView.as_view(), name='api_clear_revision'),
    url(r'^api/revision/delete/*$', api_views.DeleteRevisionView.as_view(), name='api_delete_revision'),
]

mxtracking/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="{% static "apple-touch-icon.png" %}">
        <link rel="shortcut icon" href="{% static "favicon.ico" %}">

        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% block body %}
            {% block content %}
            {% endblock content %}
        {% endblock body %}
    </body>
</html>

mxtracking/templates/layout.html
{% extends "base.html" %}
{% load staticfiles %}
{% load render_bundle from webpack_loader %}
{% load permission %}

{% block head %}
    {% block pagetitle %}<title>{% block head_title %}{% endblock %} - BTQ Maintenance Tracking System</title>{% endblock %}

    <!-- page specific og tags -->
    {% block og_tags %}{% endblock %}

    <!-- <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css" media="all" /> -->

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% render_bundle 'style' 'css' %}
    {% block pagecss %}{% endblock %}
{% endblock %}

{% block body %}
    <!--[if lt IE 8]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message|safe }}
            </div>
        {% endfor %}
    </div>
{% endif %}
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">
                                {{request.user.first_name}} {{request.user.last_name}}
                            </strong>
                            </span> <span class="text-muted text-xs block">User <b class="caret"></b></span> </span> </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="{% url 'account_logout' %}?next={{"/?busted=true"|urlencode }}">Logout</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            <img class="mini-nav-logo" src="{% static "img/gear.png" %}" />
                        </div>
                    </li>
                    {% comment %}
                    {% if request.user|can_read_inspection %}
                        <!-- <li{% if 'home' == request.resolver_match.namespace %} class="active"{% endif %}>
                            <a href="#">
                                <i class="fa fa-globe"></i> <span class="nav-label">Aircraft</span> <span class="fa arrow"></span>
                            </a>
                            <ul class="nav nav-second-level collapse">
                                <li{% if 'overview' == request.resolver_match.url_name %} class="active" {% endif %}>
                                    <a href="{% url 'home:overview' %}">Overview</a>
                                </li>
                                {% for aircraft_type in aircraft_data %}
                                    <li class="{% if aircraft_type.type == current_aircraft_type %}active{% endif %}">
                                        <a href="javascript:;">{{ aircraft_type.type }} <span class="fa arrow"></span></a>
                                        <ul class="nav nav-third-level collapse">
                                            {% for aircraft in aircraft_type.aircraft %}
                                                <li class="{% if current_aircraft_reg == aircraft.reg %}active{% endif %}">
                                                    <a href="{% url 'home:aircraft_details' reg=aircraft.reg %}">{{ aircraft.reg }}</a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li{% if 'inspection' == request.resolver_match.namespace %} class="active"{% endif %}>
                            <a href="javascript:;">
                                <i class="fa fa-gears"></i> <span class="nav-label">Inspection Programs</span> <span class="fa arrow"></span>
                            </a>
                            <ul class="nav nav-second-level collapse">
                                <li{% if 'index' == request.resolver_match.url_name and 'inspection' == request.resolver_match.namespace %} class="active" {% endif %}>
                                    <a href="{% url 'inspection:index' %}">Overview</a>
                                </li>
                            </ul>
                        </li> -->
                    {% endif %}
                    {% endcomment %}
                    {% if request.user|can_read_gantt %}
                        <li{% if 'routeplanning' == request.resolver_match.namespace %} class="active"{% endif %}>
                            <a href="javascript:;">
                                <i class="fa fa-binoculars"></i> <span class="nav-label">Route Planning Gantt</span> <span class="fa arrow"></span>
                            </a>
                            <ul class="nav nav-second-level collapse">
                                <li{% if 'view_current_published_gantt' in request.resolver_match.url_name and 'routeplanning' == request.resolver_match.namespace %} class="active" {% endif %}>
                                    <a href="{% url 'routeplanning:view_current_published_gantt' %}">View Gantt</a>
                                </li>
                                {% if request.user|can_write_gantt %}
                                    <li{% if 'index' in request.resolver_match.url_name and 'routeplanning' == request.resolver_match.namespace %} class="active" {% endif %}>
                                        <a href="{% url 'routeplanning:index' %}">Gantt Chart</a>
                                    </li>
                                    <li{% if 'flight' in request.resolver_match.url_name %} class="active" {% endif %}>
                                        <a href="{% url 'routeplanning:flights' %}">Flights</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}
                </ul>

            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" method="post" action="#">
                            <div class="form-group">
                                <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                            </div>
                        </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <a href="{% url 'account_logout' %}">
                                <i class="fa fa-sign-out"></i> Log out
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>

            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>
                        {% block page_title %}
                        {% endblock %}
                    </h2>
                    <ol class="breadcrumb">
                        {% block breadcrumb %}
                        {% endblock %}
                    </ol>
                </div>
                <div class="col-lg-2">
                </div>
            </div>

            <div class="wrapper wrapper-content">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    {% render_bundle 'vendor' %}

    {% block pagejs %}{% endblock %}

    <!-- <script>
    function makeCache() {
      if(navigator.onLine) {
        console.log('make cached version...');
        localStorage.setItem(window.location.href, $('#wrapper').html());
      }
    }

    function notifyCacheSafe() {
      $.notify({
         message: 'You are offline safe now. Flight log pages would be cached from now on'
       },{
        type: 'info'
      });
    }
    </script> -->
{% endblock %}

mxtracking/templates/site_base.html
{% extends "base.html" %}
{% load staticfiles %}
{% load render_bundle from webpack_loader %}
{% block head %}
    {% block pagetitle %}<title>{% block head_title %}{% endblock %} - Boutique Air Maintenance Tracking System</title>{% endblock %}

    <!-- page specific og tags -->
    {% block og_tags %}{% endblock %}

    <!--Global JS - head-->
    <script src="http://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% render_bundle 'style' 'css' %}
    {% render_bundle 'loginStyle' 'css' %}
{% endblock %}

{% block body %}
    <!--[if lt IE 8]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <!-- content -->
    {% block content %}
    {% endblock %}
    {% block modal %}
    {% endblock %}


    <!--Global JS - body-->

    <!--page specific js-->
      {% block pagejs %}{% endblock %}
      {% block modaljs %}{% endblock %}

{% endblock %}