home/urls.py
from django.conf.urls import url

from home import views


urlpatterns = [
    url(r'^(?P<reg>[0-9a-zA-Z]+)/*$', views.aircraft_details, name='aircraft_details'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/tasks/*$', views.aircraft_task_list, name='aircraft_task_list'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/tasks/(?P<task_id>[0-9]+)/*$', views.aircraft_task, name='aircraft_task'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/mels/*$', views.aircraft_mels, name='aircraft_mels'),
    url(r'^(?P<reg>[0-9a-zA-Z]+)/assign/*$', views.aircraft_assign_program, name='aircraft_assign'),

    url(r'^(?P<reg>[0-9a-zA-Z]+)/api/tasks/(?P<task_id>[0-9]+)/*$', views.AircraftInspectionTaskView.as_view(), name='api_aircraft_task_list'),

    url(r'^$', views.overview, name='overview'),
]

mxtracking/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('allauth.urls')),
    url(r'^aircraft/', include('home.urls', namespace='home')),
    url(r'^inspectionprogram/', include('inspection.urls', namespace='inspection')),
    url(r'^routeplanning/', include('routeplanning.urls', namespace='routeplanning')),
    url('', include('common.urls')),
]

routeplanning/urls.py
from django.conf.urls import url

from routeplanning.views import api_views
from routeplanning.views import page_views


urlpatterns = [
    url(r'^tail/add/*$', page_views.AddTailView.as_view(), name='add_tail'),
    url(r'^tail/(?P<tail_id>[0-9]+)/*$', page_views.EditTailView.as_view(), name='edit_tail'),
    url(r'^tail/(?P<tail_id>[0-9]+)/revision/(?P<revision_id>[0-9]+)/comingdue/*$',
        page_views.ComingDueView.as_view(), name='coming_due'),

    url(r'^line/add/*$', page_views.AddLineView.as_view(), name='add_line'),
    url(r'^line/(?P<line_id>[0-9]+)/*$', page_views.EditLineView.as_view(), name='edit_line'),

    url(r'^flights/*$', page_views.FlightListView.as_view(), name='flights'),
    url(r'^flights/add/*$', page_views.AddFlightView.as_view(), name='add_flight'),
    url(r'^flights/(?P<flight_id>[0-9]+)/*$', page_views.EditFlightView.as_view(), name='edit_flight'),
    url(r'^flights/delete/*$', page_views.DeleteFlightView.as_view(), name='delete_flights'),

    url(r'^$', page_views.IndexView.as_view(), name='index'),
    url(r'^view-gantt/*$', page_views.CurrentPublishedGanttView.as_view(), name='view_current_published_gantt'),

    url(r'^api/loaddata/*$', api_views.LoadDataView.as_view(), name='api_load_data'),
    url(r'^api/line/(?P<line_id>[0-9]+)/delete/*$', api_views.DeleteLineView.as_view(), name='delete_line'),
    url(r'^api/tail/(?P<tail_id>[0-9]+)/delete/*$', api_views.DeleteTailView.as_view(), name='delete_tail'),
    url(r'^api/tail/assignflight/*$', api_views.AssignFlightView.as_view(), name='api_assign_flight'),
    url(r'^api/tail/assignstatus/*$', api_views.AssignStatusView.as_view(), name='api_assign_status'),
    url(r'^api/tail/hobbs/*$', api_views.SaveHobbsView.as_view(), name='api_save_hobbs'),
    url(r'^api/tail/comingduelist/*$', api_views.ComingDueListView.as_view(), name='api_coming_due_list'),
    url(r'^api/assignment/move/*$', api_views.MoveAssignmentView.as_view(), name='api_move_assignment'),
    url(r'^api/assignment/remove/*$', api_views.RemoveAssignmentView.as_view(), name='api_remove_assignment'),
    url(r'^api/assignment/resize/*$', api_views.ResizeAssignmentView.as_view(), name='api_resize_assignment'),
    url(r'^api/flight/uploadcsv/*$', api_views.UploadCSVView.as_view(), name='api_upload_csv'),
    url(r'^api/flight/getpage/*$', api_views.FlightListView.as_view(), name='api_flight_get_page'),
    url(r'^api/hobbs/(?P<hobbs_id>[0-9]+)/*$', api_views.HobbsView.as_view(), name='api_hobbs'),
    url(r'^api/revision/publish/*$', api_views.PublishRevisionView.as_view(), name='api_publish_revision'),
    url(r'^api/revision/clear/*$', api_views.ClearRevisionView.as_view(), name='api_clear_revision'),
    url(r'^api/revision/delete/*$', api_views.DeleteRevisionView.as_view(), name='api_delete_revision'),
]

routeplanning/forms.py
from django import forms
from django.forms import ModelForm

from routeplanning.models import *


class TailForm(ModelForm):
    class Meta:
        model = Tail
        fields = '__all__'


class LineForm(forms.Form):
    name = forms.CharField(label='Name', required=True)
    part1 = forms.CharField(label='Part of Line 1', required=True)
    part2 = forms.CharField(label='Part of Line 2', required=False)
    part3 = forms.CharField(label='Part of Line 3', required=False)
    part4 = forms.CharField(label='Part of Line 4', required=False)
    part5 = forms.CharField(label='Part of Line 5', required=False)
    part6 = forms.CharField(label='Part of Line 6', required=False)
    part7 = forms.CharField(label='Part of Line 7', required=False)
    part8 = forms.CharField(label='Part of Line 8', required=False)
    part9 = forms.CharField(label='Part of Line 9', required=False)
    part10 = forms.CharField(label='Part of Line 10', required=False)
    part11 = forms.CharField(label='Part of Line 11', required=False)
    part12 = forms.CharField(label='Part of Line 12', required=False)

    class Meta:
        fields = ('name',)


class FlightForm(ModelForm):
    class Meta:
        model = Flight
        fields = '__all__'


class DeleteMultipleFlightsForm(forms.Form):
    flight_ids = forms.CharField(label='Flight IDs', required=True)

    class Meta:
        fields = ('flight_ids',)

routeplanning/views.py
from datetime import timedelta, datetime
import json
import dateutil.parser
import random
import os
import csv
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseForbidden
from django.middleware import csrf
from django.db.models import Q, ProtectedError, Max
from django.conf import settings
from django.urls import reverse
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from rest_framework.response import Response

from routeplanning.models import *
from routeplanning.forms import *
from common.helpers import *
from common.decorators import *


def gantt_page_context(request, read_only):
    if request.GET.get('mode'):
        mode = request.GET.get('mode')
    elif 'mode' in request.session:
        mode = request.session['mode']
    else:
        mode = '4'

    start_tmstmp = int(request.GET.get('start')) if request.GET.get('start') else 0
    end_tmstmp = int(request.GET.get('end')) if request.GET.get('end') else 0
    if not(start_tmstmp or end_tmstmp):
        start_tmstmp = request.session['start_tmstmp'] \
            if 'start_tmstmp' in request.session \
            else None

    tails = Tail.objects.all()
    lines = Line.objects.order_by('name').all()

    days_options = { '1': 1, '2': 1, '3': 1, '4': 1, '5': 3, '6': 7, }          # Date mark count
    hours_options = { '1': 3, '2': 6, '3': 12, '4': 24, '5': 24, '6': 6, }      # Hours mark count
    units_per_hour_options = { '1': 4, '2': 2, '3': 1, '4': 1, '5': 1, '6': 0.25, }

    days = days_options[mode]

    hours = hours_options[mode]
    units_per_hour = units_per_hour_options[mode]

    if not start_tmstmp:
        if end_tmstmp:
            start_tmstmp = int(end_tmstmp) - 14 * 24 * 3600
        else:
            start_time = datetime_now_utc()
            start_time = start_time.replace(hour=0, minute=0, second=0, microsecond=0)
            start_tmstmp = totimestamp(start_time)

    big_unit_colspan = units_per_hour * hours if units_per_hour > 1 else hours
    big_unit_count = 14 * (24 / hours) if days == 1 else 14
    table_length_in_secs = 14 * 24 * 3600

    return {
        'tails': tails,
        'lines': lines,
        'big_units': big_unit_count,
        'small_units': big_unit_colspan * big_unit_count,
        'days': days,
        'hours': hours,
        'big_unit_colspan': big_unit_colspan,
        'units_per_hour': units_per_hour,
        'mode': mode,
        'start_tmstmp': start_tmstmp,
        'end_tmstmp': end_tmstmp,
        'start_param_exists': 'true' if request.GET.get('start') or 'start_tmstmp' in request.session else 'false',
        'end_param_exists': 'true' if request.GET.get('end') else 'false',
        'prev_start_tmstmp': int(start_tmstmp) - table_length_in_secs,
        'next_start_tmstmp': int(start_tmstmp) + table_length_in_secs,
        'csrf_token': csrf.get_token(request),
        'window_at_end': request.GET.get('window_at_end') or 0,
        'revisions': Revision.objects.order_by('-published_datetime'),
        'read_only': read_only,
    }

def update_session(request, context_data):
    request.session['mode'] = context_data['mode']
    request.session['start_tmstmp'] = context_data['start_tmstmp']

@login_required
@gantt_readable_required
def index(request):
    context = gantt_page_context(request, not can_write_gantt(request.user))
    context['page'] = 'routeplanning:index'
    update_session(request, context)
    return render(request, 'gantt.html', context)

@login_required
@gantt_readable_required
def view_current_published_gantt(request):
    context = gantt_page_context(request, True)
    context['page'] = 'routeplanning:view_current_published_gantt'
    update_session(request, context)
    return render(request, 'gantt.html', context)

@login_required
@gantt_writable_required
def add_tail(request):
    form = TailForm(request.POST or None)
    action_after_save = request.POST.get('action_after_save')

    if request.method == 'POST':
        if form.is_valid():
            tail = form.save()

            if action_after_save == 'save-and-continue':
                return redirect('routeplanning:edit_tail', tail_id=tail.id)
            elif action_after_save == 'save':
                return redirect('routeplanning:index')
            elif action_after_save == 'save-and-add-another':
                form = TailForm()

    tails = Tail.objects.all()
    context = {
        'form': form,
        'title': 'Add Tail',
        'tails': tails,
        'csrf_token': csrf.get_token(request),
    }
    return render(request, 'tail.html', context)

@login_required
@gantt_readable_required
def edit_tail(request, tail_id=None):
    tail = get_object_or_404(Tail, pk=tail_id)

    form = TailForm(request.POST or None, instance=tail)
    action_after_save = request.POST.get('action_after_save')

    if request.method == 'POST':
        if not can_write_gantt(request.user):
            return HttpResponseForbidden()
        if form.is_valid():
            tail = form.save()

            if action_after_save == 'save-and-add-another':
                return redirect('routeplanning:add_tail')
            elif action_after_save == 'save':
                return redirect('routeplanning:index')
            elif action_after_save == 'save-and-add-another':
                form = LineForm()

    tails = Tail.objects.all()
    context = {
        'form': form,
        'title': 'Edit Tail ' + tail.number,
        'tails': tails,
        'csrf_token': csrf.get_token(request),
    }
    return render(request, 'tail.html', context)

@login_required
@gantt_writable_required
@api_view(['DELETE'])
def delete_tail(request, tail_id=None):
    result = {
        'success': False,
    }

    try:
        tail = Tail.objects.get(pk=tail_id)
        tail.delete()
        result['success'] = True
    except:
        result['error'] = 'Error occurred while deleting tail'

    return Response(result)

@login_required
@gantt_writable_required
def coming_due(request, tail_id=None, revision_id=None):
    tail = Tail.objects.get(pk=tail_id)

    context = {
        'tail': tail,
        'tails': [],
        'revision_id': revision_id if revision_id else 0,
        'csrf_token': csrf.get_token(request),
    }
    return render(request, 'comingdue.html', context)

@login_required
@gantt_writable_required
def add_line(request):
    form = LineForm(request.POST or None)
    action_after_save = request.POST.get('action_after_save')

    if request.method == 'POST':
        if form.is_valid():
            line = Line(name=form.cleaned_data['name'])    
            line.save()

            for i in range(1, 12):
                entered_line_part_number = form.cleaned_data['part' + str(i)]
                if entered_line_part_number:
                    line_part = LinePart(number=entered_line_part_number, line=line)    
                    line_part.save()
                else:
                    break

            if action_after_save == 'save-and-continue':
                return redirect('routeplanning:edit_line', line_id=line.id)
            elif action_after_save == 'save-and-add-another':
                form = LineForm()
            elif action_after_save == 'save':
                return redirect('routeplanning:index')

    lines = Line.objects.all()
    context = {
        'form': form,
        'title': 'Add Line',
        'lines': lines,
        'csrf_token': csrf.get_token(request),
    }
    return render(request, 'line.html', context)

@login_required
@gantt_readable_required
def edit_line(request, line_id=None):
    line = get_object_or_404(Line, pk=line_id)

    initialData = {
        'name': line.name,
    }
    for i, line_part in enumerate(line.linepart_set.all()):
        initialData['part' + str(i)] = line_part.number

    form = LineForm(request.POST or initialData)
    action_after_save = request.POST.get('action_after_save')

    if request.method == 'POST':
        if not can_write_gantt(request.user):
            return HttpResponseForbidden()
        if form.is_valid():
            if line.name != form.cleaned_data['name']:
                line.name = form.cleaned_data['name']
                line.save()

            line.linepart_set.all().delete()

            for i in range(1, 12):
                entered_line_part_number = form.cleaned_data['part' + str(i)]
                if entered_line_part_number:
                    line_part = LinePart(number=entered_line_part_number, line=line)    
                    line_part.save()
                else:
                    break

            if action_after_save == 'save-and-add-another':
                return redirect('routeplanning:add_line')
            elif action_after_save == 'save':
                return redirect('routeplanning:index')
            elif action_after_save == 'save-and-add-another':
                form = LineForm()

    lines = Line.objects.all()
    context = {
        'form': form,
        'title': 'Edit Line ' + line.name,
        'lines': lines,
        'csrf_token': csrf.get_token(request),
    }
    return render(request, 'line.html', context)

@login_required
@gantt_writable_required
@api_view(['DELETE'])
def delete_line(request, line_id=None):
    result = {
        'success': False,
    }

    try:
        if line_id:
            line = Line.objects.get(pk=line_id)
            line.delete()
            result['success'] = True
        else:
            result['error'] = 'Line id should be specified'
    except:
        result['error'] = 'Error occurred while deleting line'

    return Response(result)

@login_required
@gantt_readable_required
def flights(request):
    flights = []

    context = {
        'flights': flights,
        'csrf_token': csrf.get_token(request),
    }

routeplanning/templates/comingdue.html
{% extends "layout.html" %}
{% load staticfiles %}
{% load permission %}
{% load tz %}

{% block head_title %}Coming Due {{ tail.number }}{% endblock %}

{% block page_title %}
    Coming Due {{ tail.number }}
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'routeplanning:index' %}">
                Route Planning Gantt
            </a>
        </li>
        <li class="active">
            <strong>Coming Due {{ tail.number }}</strong>
        </li>
    </ol>
{% endblock %}

{% block content %}
    <div id="coming-due-list">
    </div>
{% endblock %}

{% block pagejs %}
    <script type="text/javascript">
        window.initComingDueListPage('#coming-due-list', {
            tailId: {{ tail.id }},
            tailNumber: "{{ tail.number }}",
            revision: {{ revision_id }},
            comingDueListAPI: '{% url 'routeplanning:api_coming_due_list' %}',
            loadHobbsAPIBase: '{% url 'routeplanning:api_hobbs' hobbs_id=0 %}',
            saveHobbsAPI: '{% url 'routeplanning:api_save_hobbs' %}',
            urlToRedirectAfterSave: '{% url 'routeplanning:index' %}',
            {% if request.user|can_write_gantt %}
                writable: true,
            {% else %}
                writable: false,
            {% endif %}
        });
    </script>
{% endblock %}

routeplanning/templates/flight.html
{% extends "layout.html" %}
{% load staticfiles %}
{% load addclass %}

{% block head_title %}{{ title }}{% endblock %}

{% block page_title %}
    {{ title }}
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'routeplanning:index' %}">
                Route Planning Gantt
            </a>
        </li>
        <li>
            <a href="{% url 'routeplanning:flights' %}">
                Flights
            </a>
        </li>
        <li class="active">
            <strong>{{ title }}</strong>
        </li>
    </ol>
{% endblock %}

{% block content %}
    <div class="ibox">
        <div class="ibox-title">
            <h3>{{ title }}</h3>
        </div>
        <div class="ibox-content">
            <div class="row">
                <div class="col-lg-6 col-md-8 col-sm-10 col-xs-12">
                    <form class="form-horizontal" action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="{{ field.name }}">{{ field.label }}</label>
                                <div class="col-sm-8">
                                    {{ field.errors }}
                                    {{ field | addclass:'form-control' }}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="text-right m-t-lg">
                            <button class="btn btn-primary" type="submit">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

routeplanning/templates/flights.html
{% extends "layout.html" %}
{% load staticfiles %}
{% load addclass %}

{% block head_title %}Flights{% endblock %}

{% block page_title %}
    Flights
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'routeplanning:index' %}">
                Route Planning Gantt
            </a>
        </li>
        <li class="active">
            <strong>Flights</strong>
        </li>
    </ol>
{% endblock %}

{% block content %}
    <form method="POST" id="edit-form" class="hidden">
        {% csrf_token %}
        <input type="hidden" class="flight-ids" name="flight_ids" />
        <!-- more params -->
    </form>
    <form method="POST" action="{% url 'routeplanning:delete_flights' %}" id="delete-form" class="hidden">
        {% csrf_token %}
        <input type="hidden" class="flight-ids" name="flight_ids" />
    </form>
    <div class="ibox">
        <div class="ibox-title">
            <h3>Flights</h3>
        </div>
        <div class="ibox-content">
            <div class="m-b">
                <a href="{% url 'routeplanning:add_flight' %}" class="btn btn-w-m btn-primary">Create Flight</a>
                <a href="javascript:void();" class="btn btn-w-m btn-primary" data-toggle="modal" data-target="#upload-csv-modal">Upload CSV File</a>
            </div>
            <div class="clearfix">
                <table id="flights-table" class="datatable table table-stripped toggle-arrow-tiny"
                    data-name="flights_table"
                    data-default-sort-column="0"
                    data-responsive="true"
                    data-timestamp-columns="4,5,6,7,8,9,10,11,12,13,14,15"
                    data-ajax-url="{% url 'routeplanning:api_flight_get_page' %}"
                    data-ajax-csrf-token="{{ csrf_token }}">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Number</th>
                            <th>Origin</th>
                            <th>Destination</th>
                            <th><span style="white-space: nowrap;">Scheduled OUT Time</span></th>
                            <th><span style="white-space: nowrap;">Scheduled OFF Time</span></th>
                            <th><span style="white-space: nowrap;">Scheduled ON Time</span></th>
                            <th><span style="white-space: nowrap;">Scheduled IN Time</span></th>
                            <th><span style="white-space: nowrap;">Estimated OUT Time</span></th>
                            <th><span style="white-space: nowrap;">Estimated OFF Time</span></th>
                            <th><span style="white-space: nowrap;">Estimated ON Time</span></th>
                            <th><span style="white-space: nowrap;">Estimated IN Time</span></th>
                            <th><span style="white-space: nowrap;">Actual OUT Time</span></th>
                            <th><span style="white-space: nowrap;">Actual OFF Time</span></th>
                            <th><span style="white-space: nowrap;">Actual ON Time</span></th>
                            <th><span style="white-space: nowrap;">Actual IN Time</span></th>
                            <th data-sortable="false"></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <div class="modal inmodal fade" id="upload-csv-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-md">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h5 class="modal-title">Upload File</h5>
                </div>
                <div class="modal-body">
                    <h4>Upload File</h4>
                    <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                        <div class="form-control" data-trigger="fileinput">
                            <i class="glyphicon glyphicon-file fileinput-exists"></i>
                            <span class="fileinput-filename"></span>
                        </div>
                        <span class="input-group-addon btn btn-default btn-file">
                            <span class="fileinput-new">Select file</span>
                            <span class="fileinput-exists">Change</span>
                            <input type="file" id="csvfile" />
                        </span>
                        <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                    </div>
                    <div class="upload-progress m-t hidden">
                        <h5 class="status">Uploading...</h5>
                        <div class="progress progress-bar-default">
                            <div class="progress-bar" style="width: 0%">
                            </div>
                        </div>
                    </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary btn-upload-csv">Upload</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block pagejs %}
    <script type="text/javascript">
        function setUploadProgress(progress, status) {
            var $progressContainer = $('.upload-progress');
            $progressContainer.find('.progress-bar').css('width', progress + '%');
            $progressContainer.find('.status').html(status);
        }

        $('#flights-table').on('click', '.btn-delete-flight', function(e) {
            e.stopPropagation();
            var $row = $(this).closest('tr');
            var flightsTable = window.datatables.get('flights_table');
            var data = flightsTable.rows($row).data();
            if (data.length > 0) {
                var id = data[0][0];
                var $form = $('#delete-form');
                $form.find('.flight-ids').val(id);
                $form.submit();
            }
        });

        $('.btn-upload-csv').on('click', function(e) {
            e.preventDefault();

            var files = $('#csvfile')[0].files;
            if (!files.length) {
                alert('Please select a file to upload.');
                return;
            }

            var $btn = $(this);
            $('.upload-progress').removeClass('hidden');
            $btn.attr('disabled', true);

            var formData = new FormData();
            formData.append('csvfile', files[0]);
            formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
            $.ajax({
                method: 'POST',
                url: '{% url 'routeplanning:api_upload_csv' %}',
                data: formData,
                processData: false,
                contentType: false,
                xhr: function(){
                    var xhr = $.ajaxSettings.xhr();
                    xhr.upload.onprogress = function(evt) {
                        setUploadProgress(evt.loaded / evt.total * 100, 'Uploading...');
                    };
                    xhr.upload.onload = function() {
                        setUploadProgress(100, 'Upload done. Processing...');
                    };
                    return xhr;
                },
            })
            .then(function(response) {
                setUploadProgress(100, 'Finished.');
                $btn.attr('disabled', false);
            }, function() {
                setUploadProgress(100, 'Error occurred.');
                $btn.attr('disabled', false);
            });
        });
    </script>
{% endblock %}

routeplanning/templates/gantt.html
{% extends "layout.html" %}
{% load staticfiles %}
{% load permission %}

{% block head_title %}Route Planning Gantt{% endblock %}

{% block page_title %}
    Route Planning Gantt
{% endblock %}

{% block pagecss %}
    <style type="text/css">
        .page-heading {
            display: none;
        }
    </style>
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li class="active">
            <strong>Route Planning Gantt</strong>
        </li>
    </ol>
{% endblock %}

{% block content %}
    <div id="gantt-container">
    </div>
{% endblock %}

{% block pagejs %}
    <script type="text/javascript">
        var readOnly = {% if read_only %}true{% else %}false{% endif %};
        var unit = 3600 / {{ units_per_hour }};
        var lines = [
            {% for line in lines %}
            {
                id: {{ line.id }},
                name: "{{ line.name }}",
            },{% endfor %}
        ];
        var tails = [
            {% for tail in tails %}{
                id: {{ tail.id }},
                number: "{{ tail.number }}",
            },
            {% endfor %}
        ];
        var initialRevisions = [
            {% for revision in revisions %}{
                id: {{ revision.id }},
                published_datetime: "{{ revision.published_datetime|date:'c' }}",
                has_draft: {% if revision.has_draft %}true{% else %}false{% endif %},
            },
            {% endfor %}
        ];

        /* Gantt table init */

        window.initGantt('#gantt-container', {
            lines: lines,
            tails: tails,
            initialRevisions: initialRevisions,
            ganttURL: "{% url page %}",
            addTailURL: "{% url 'routeplanning:add_tail' %}",
            addLineURL: "{% url 'routeplanning:add_line' %}",
            editLineURL: "{% url 'routeplanning:edit_line' line_id=0 %}",
            loadDataAPIUrl: "{% url 'routeplanning:api_load_data' %}",
            assignFlightAPIUrl: "{% url 'routeplanning:api_assign_flight' %}",
            assignStatusAPIUrl: "{% url 'routeplanning:api_assign_status' %}",
            moveAssignmentAPIUrl: "{% url 'routeplanning:api_move_assignment' %}",
            removeAssignmentAPIUrl: "{% url 'routeplanning:api_remove_assignment' %}",
            resizeAssignmentAPIUrl: "{% url 'routeplanning:api_resize_assignment' %}",
            publishRevisionAPIUrl: "{% url 'routeplanning:api_publish_revision' %}",
            clearRevisionAPIUrl: "{% url 'routeplanning:api_clear_revision' %}",
            deleteRevisionAPIUrl: "{% url 'routeplanning:api_delete_revision' %}",
            days: {{ days }},
            hours: {{ hours }},
            unit: unit,
            writable: !readOnly,
            mode: {{ mode }},
            startTmstmp: {{ start_tmstmp }},
            prevStartTmstmp: {{ prev_start_tmstmp }},
            nextStartTmstmp: {{ next_start_tmstmp }},
            bigUnits: {{ big_units }},
            smallUnits: {{ small_units }},
            windowAtEnd: {{ window_at_end }},
            startParamExists: {{ start_param_exists }},
            endParamExists: {{ end_param_exists }},
        });
    </script>
{% endblock %}